### PR TITLE
Enhanced/optimized backup

### PR DESCRIPTION
**Pull request by sriccio**
Some proposed enhancement, mostly for databases dump.

- Using xz for compression (better compression, not sure if it's faster though)
- Now mysql dumps are directly compressed to separate backup files (to save time, disk space and disk writes)
- Configuration option to skip data for big mailscanner log tables (maillog, mtalog, mtalog_ids) in case you don't want to daily dump your 20gb of logs.
- Now use a config file (that could be edited through cli GUI?). With defaults if config file is not found.
- Some misc bash syntax changes to avoid complaints from your bash editor syntax checker

### CODE REVIEW

**Comment by sriccio** [comment]
This is work in progress for review and request for comments.

I still need to apply changes to `func_systemrestore` to take the changes into account in case of a emergency restore operation and also add creation of `/etc/eFa/Backup-Config` at install.

**Comment by shawniverson** [comment]
Sounds good, I'll take a look.  Right now I'm working on MailScanner stuff and will bring my attention back to eFa soon.

**Comment by sriccio** [comment]
Hi @shawniverson,

No problem, I will keep updating the branch on my side with the few things to be adapted for the restore function to match the "new" backup script.

**Comment by shawniverson** [comment]
Any updates on this PR @sriccio ?

**Comment by sriccio** [comment]
Hello @shawniverson, 

on my side the changes to the backup script are working well. It reduced the load and disk usage of daily backups drastically.

I sill need to finish editing the restore function to match it and will update my branch with the changes in a few days.

**Comment by shawniverson** [comment]
Need to close this PR due to maintenance of the repo.

@sriccio Please resubmit the PR when you are ready.

**Comment by sriccio** [comment]
No prob, I will reapply the commits/PR on a branch current with current master.

**Pull request closed without merging**
